### ISSUE TITLE
URL for downloading UniRef30 hhsuite database not valid

### ISSUE THREAD

**Issue by ajbordner** [uw-ipd/RoseTTAFold2#27]
The URL given in the instructions for downloading the UniRef30 hhsuite database http://wwwuser.gwdg.de/~compbiol/uniclust/2020_06/UniRef30_2020_06_hhsuite.tar.gz
is no longer working.

If possible, could you please provide another source (mirror) for this file.

**Comment by ExactMoose** [comment]
I am having the same issue. I found a [Microsoft Azure article](https://techcommunity.microsoft.com/t5/azure-compute-blog/build-your-rosettafold-protein-ai-prediction-cluster-on-azure/ba-p/2631158) which seems to have the database hosted on their own server, but I think you have to set up your server the way they suggest to get access.
