### ISSUE TITLE
Small question regarding `atom27` vs `atom14` representation

### ISSUE THREAD

**Issue by amorehead** [uw-ipd/RoseTTAFold2#35]
Hello. Referencing the following line of code, I was curious, "Throughout RoseTTAFold2's codebase, is the `atom27` representation of a given protein structure precisely the same as the `atom14` representation except for having 13 additional atoms appended to the end?". I ask because I was wondering whether it is correct to assume that one can slice the first 14 atoms from an `atom27`-shaped tensor to extract an equivalent tensor of `atom14`-shape (since such an operation would not be correct in different codebases such as that of AlphaFold 2 as the `atom14` and `atom37` tensors there have atoms in slightly different orders per residue).

https://github.com/uw-ipd/RoseTTAFold2/blob/a26f29bb92d4946ef8bf225edba9240c9e647747/network/train_multi_deep.py#L199

**Comment by fdimaio** [comment]
Hello,  You indeed can slice the 1st 14 columns to get a H-free structure.  Residue hydrogens always start at index 14.

**Comment by amorehead** [comment]
Thanks for clarifying!
