### ISSUE TITLE
Specify database location

### ISSUE THREAD

**Issue by akashbahai** [uw-ipd/RoseTTAFold2#8]
Hi,
Thanks for providing the source code for your method. This is slightly off-topic but I was wondering if was possible to specify the location of databases such as Uniref, bfd or PDB. I am using RosettaFold2NA, Alphafold etc and it's not possible to have all of these downloaded separately for each program.

**Comment by Qmi3** [comment]
Hello, i have met the same problem and i define a new variable DATADIR=/path/to/mydatabase,and replace all of the $PIPEDIR ahead of  the row of database in the run_RF2NA.sh,and that works

**Comment by akashbahai** [comment]
@Qmi3 Thanks for the comment. This should work for me.
